require 'redis'

class Shortener < ActiveRecord::Base
  attr_accessible :url, :shortlink

  validates :url, :presence => true, :uniqueness => true, :http_uri_format => true

  before_save :set_autogenerated_info

  def shortlink
    "http://#{domain}/#{key}"
  end

  private
    def set_autogenerated_info
      domain = get_random_domain
      key = get_next_key(domain)
      write_attribute(:domain, domain)
      write_attribute(:key, key)
    end

    def get_random_domain
      REDIS.SRANDMEMBER('domains')
    end

    def get_next_key(domain)
      [REDIS.incr(domain).to_i].pack("U*").mb_chars
    end
end
